// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSZYbrHQuxV_jzf9Sn6efhvXakLbWCkA',
    appId: '1:257112677853:web:833bb80147e21d6081aa34',
    messagingSenderId: '257112677853',
    projectId: 'my-music-de1fe',
    authDomain: 'my-music-de1fe.firebaseapp.com',
    storageBucket: 'my-music-de1fe.appspot.com',
    measurementId: 'G-1LE9CH3WPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMxnxV4z8pIxr0-DAymyWEbboufvblU2o',
    appId: '1:257112677853:android:bcfa5e937533921781aa34',
    messagingSenderId: '257112677853',
    projectId: 'my-music-de1fe',
    storageBucket: 'my-music-de1fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABMNJv8zbW_p8-sfwskrL-XrVc9pjkaZM',
    appId: '1:257112677853:ios:73b51daddabaf31381aa34',
    messagingSenderId: '257112677853',
    projectId: 'my-music-de1fe',
    storageBucket: 'my-music-de1fe.appspot.com',
    iosBundleId: 'com.example.myMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABMNJv8zbW_p8-sfwskrL-XrVc9pjkaZM',
    appId: '1:257112677853:ios:73b51daddabaf31381aa34',
    messagingSenderId: '257112677853',
    projectId: 'my-music-de1fe',
    storageBucket: 'my-music-de1fe.appspot.com',
    iosBundleId: 'com.example.myMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSZYbrHQuxV_jzf9Sn6efhvXakLbWCkA',
    appId: '1:257112677853:web:d9b8585dbba623f481aa34',
    messagingSenderId: '257112677853',
    projectId: 'my-music-de1fe',
    authDomain: 'my-music-de1fe.firebaseapp.com',
    storageBucket: 'my-music-de1fe.appspot.com',
    measurementId: 'G-MHL5HN17XN',
  );
}
